In [1]:
import numpy as np

In [2]:
np.__version__

'1.19.2'

In [3]:
l1 = np.arange(1,10)
l1 = l1.reshape((3,3))


In [4]:
l1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:

l2 = np.arange(2*2*5).reshape((2,2,5))
l2

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [11]:
type(l1)

numpy.ndarray

In [18]:
 import numpy as np
a = np.array([2,3,4])
print (a)
a.dtype
b = np.array([1.2, 3.5, 5.1])
b.dtype


[2 3 4]


dtype('float64')

In [19]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.ones( (2,3,4), dtype=np.int16 ) 

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [21]:
np.empty( (2,3) )

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.arange( 10, 50, 5 )

array([10, 15, 20, 25, 30, 35, 40, 45])

In [23]:
np.linspace( 0, 7, 12 )                 # 12 numbers from 0 to 7

array([0.        , 0.63636364, 1.27272727, 1.90909091, 2.54545455,
       3.18181818, 3.81818182, 4.45454545, 5.09090909, 5.72727273,
       6.36363636, 7.        ])

In [24]:
np.linspace( 0, 10, 5 )   

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [25]:
A = np.array( [[1,1],
               [0,1]] )

In [26]:
B = np.array( [[2,0],
             [3,4]] )

In [27]:
A * B                       # elementwise product

array([[2, 0],
       [0, 4]])

In [28]:
A @ B                       # matrix product

array([[5, 4],
       [3, 4]])

In [29]:
A.dot(B)                    # another matrix product

array([[5, 4],
       [3, 4]])

In [30]:
a.sum()


9

In [31]:
a.min()

2

In [32]:
a.max()


4

In [35]:
b = np.arange(12).reshape(3,4)
print (b)

b.sum(axis=0)                            # sum of each column

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([12, 15, 18, 21])

In [36]:
b.min(axis=1)                            # min of each row


array([0, 4, 8])

In [37]:
b.cumsum(axis=1)                         # cumulative sum along each row

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

In [46]:
B = np.arange(3)
print (B)

print ("exp \n {}", np.exp(B) )

print (np.sqrt(B))

C = np.array([2., -1., 4.])
np.add(B, C)

[0 1 2]
exp 
 {} [1.         2.71828183 7.3890561 ]
[0.         1.         1.41421356]


array([2., 0., 6.])

In [48]:
def f(x,y):
    return 10*x+y

b = np.fromfunction(f,(5,4),dtype=int)
b

print (" Print b[2,3] \n ", b[2,3] )

print (" Print b[0:5, 1] \n ", b[0:5, 1] )                      # each row in the second column of b

print (" Print b[ : ,1] \n ", b[ : ,1])                        # equivalent to the previous example

print (" Print b[1:3, : ]  \n ", b[1:3, : ] )                     # each column in the second and third row of b


 Print b[2,3] 
  23
 Print b[0:5, 1] 
  [ 1 11 21 31 41]
 Print b[ : ,1] 
  [ 1 11 21 31 41]
 Print b[1:3, : ]  
  [[10 11 12 13]
 [20 21 22 23]]


In [53]:
a = np.arange(5)
a[[0,0,2]]=[1,2,3]
a

array([2, 1, 3, 3, 4])